# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: exiftool
        name: Run exif tool
        language: system
        types: ["image"]
        entry: exiftool -all= --icc_profile:all -tagsfromfile @ -orientation -overwrite_original
        exclude_types:
          - svg
